version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11.0

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Configure environment and docker login
          command: |
            . gcloud/configure.sh
            docker login -u _json_key -p "$(cat ~/gcp-key.json)" https://eu.gcr.io
      - run:
          name: Setup integration test dependencies
          command: docker-compose -f compose/test/docker-compose.yaml up -d

      - run: 
          name: Building test environment
          command: docker build -t testimage .

      - run:
          name: Run tests
          command: docker run -it --net test_default --name test testimage sh -c "NODE_ENV=citest yarn citest"

      - run: 
          name: Clean up integration test dependencies
          command: docker rm -f test && docker-compose -f compose/test/docker-compose.yaml down

  publish:
    <<: *defaults
    steps:
      - checkout

      # - run:
      #     name: Authenticate with registry
      #     command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          context: org-global
          filters:
            tags:
              only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/
            branches:
              ignore: /.*/